# Python : Numpy 

### numpy provides the excellent ndarray objects, short for n-dimensional arrays.

#### In a ‘ndarray’ object, aka ‘array’, you can store multiple items of the same data type. It is the facilities around the array object that makes numpy so convenient for performing math and data manipulations.

#### numpy provides a basic feature of vectorized operation which is not available with list

In [2]:
# import numpy package

import numpy as np

In [3]:
# Check the numpy version 

np.__version__

'1.16.2'

In [79]:
np.version.full_version

'1.16.2'

In [4]:
# Here is a list datastructure containing a set of numbers 

List_Num = [1,2,3,4]

List_Num

[1, 2, 3, 4]

In [82]:
# Now , lets try to add 4 to each element of the list

List_Num + 2

TypeError: can only concatenate list (not "int") to list

In [5]:
# Now let's convert list variable to ndarray and then try to add 2 to each element 

Array_Num = np.array(List_Num)

Array_Num

array([1, 2, 3, 4])

In [6]:
# Add 2 to each element of array 
Array_Num + 2

array([3, 4, 5, 6])

## Attributes of ndarray 

In [7]:
# The data pointer indicates the memory address of the first byte in the array

Array_Num.data

In [8]:
# dtype pointer describes the kind of elements that are contained within the array

Array_Num.dtype

dtype('int32')

In [9]:
# The shape indicates the shape of the array

Array_Num.shape

(4,)

In [10]:
array_2d = np.array([[1,2,3],[4,5,6]])

array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array_2d.shape

(2, 3)

In [12]:
# The strides are the number of bytes that should be skipped in memory to go to the next 
# element. If your strides are (10,1), you need to proceed one byte to get to the next column
# and 10 bytes to locate the next row.

Array_Num.strides

(4,)

In [13]:
# get the number of elements in an array

len(Array_Num)

4

In [14]:
# get the number of elements in an array

len(np.array([[1,2,3],[4,5,6]]))

2

In [15]:
# get the number of dimensions of an Array

np.array([[1,2,3],[4,5,6]]).ndim

2

In [16]:
Array_Num

array([1, 2, 3, 4])

In [17]:
# get the number of dimensions of an Array

Array_Num.ndim

1

In [18]:
# Total number of individual data elements in an array

Array_Num.size

4

In [19]:
# Total number of individual data elements in an array

np.array([[1,2,3],[4,5,6]]).size

6

In [20]:
Array_Num.dtype.name

'int32'

In [21]:
# 1 Dimensional Array or Rank-1 Array 

a = np.array([1,5,0]) 

a

print(a)

print(type(a))

print(a.shape)



[1 5 0]
<class 'numpy.ndarray'>
(3,)


#### Accessing the elements of an Array

In [23]:
print(a)

# Access the first element of Rank-1 ( 1D ) Array
print(a[0])

# Access the last element of Rank-1 ( 1D ) Array
print(a[-1])

# Access the second element of Rank-1 ( 1D ) Array
print(a[1])

# Access the second last element of Rank-1 ( 1D ) Array
print(a[-2])

[1 5 0]
1
0
5
5


In [24]:
# Updating the elemenst of an Array

print(a[2])

a[2] = 8

print(a[2])

0
8


In [25]:
# 2 Dimensional Array or array of Rank - 2 

B = np.array([[1, 2 , 3], [ 4 , 5 , 6]]) 

print(B)



[[1 2 3]
 [4 5 6]]


In [26]:
print(type(B))


<class 'numpy.ndarray'>


In [31]:
print(B.shape)



(2, 3)


In [27]:
# Access the elements of 2-D Array

print(B[1,2])

print(B[1,1])

print(B)

6
5
[[1 2 3]
 [4 5 6]]


In [28]:
print(B[ : , 2])

type(B[ : , 2])

[3 6]


numpy.ndarray

In [184]:
print(B[ 1 , :])

[4 5 6]


## Various Functions from Numpy package

In [186]:
# 1) Create an Array of Zeroes 

Zero_Array = np.zeros((2,3))

Zero_Array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# 2) Create an Array of Ones

Ones_Array = np.ones((3,4) )

Ones_Array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [187]:
Ones_Array = np.ones((3,4) , dtype=int)

Ones_Array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
# 3) Create an Array of Constants

Constant_Array = np.full((2,4) , 8)

Constant_Array

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [188]:
# 4) Create an Identity Matrix / Array 

Identity_Array = np.eye(4 , dtype=int)


Identity_Array

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [199]:
# 5) Creating an array of Random numnbers

Random_Array = np.random.random( (3 , 4) )

print(Random_Array)

print("\n " )

print(Random_Array * 2)

[[0.15453353 0.79213974 0.34957859 0.94210354]
 [0.59543268 0.03489204 0.23058148 0.95961677]
 [0.67404908 0.74636557 0.84978652 0.66780347]]

 
[[15.45335252 79.21397354 34.95785937 94.21035372]
 [59.54326845  3.4892038  23.0581484  95.96167731]
 [67.4049076  74.63655655 84.97865167 66.78034679]]


In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
np.arange(2,15,2)

array([ 2,  4,  6,  8, 10, 12, 14])

## Accessing elements of an Array 

In [200]:
B = np.array([[1, 2 , 3], [ 4 , 5 , 6] , [7,8,9]]) 

print(B )



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [201]:
print("\n")

print(B.shape)

print("\n")





(3, 3)




In [35]:
print(B[1,2])

# OR 

print(B[1][2])


print("\n")

print(B[ : , 2])

print("\n")

print(B[ 1 , :])

6
6


[3 6]


[4 5 6]


In [203]:
B = np.array([[1, 2 , 3], [ 4 , 5 , 6] , [7,8,9] , [10,11,12]]) 

print(B )



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [206]:
print("\n")

print(B[:,1:3 ])



[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


### Boolean / Logical Indexing

In [30]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
B > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [32]:
print(B[B > 2])

print(B[B > 2].shape)

[3 4 5 6]
(4,)


In [207]:
C = B[:,0:2 ]

C

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [208]:
B[0,1] = 99

B

array([[ 1, 99,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [209]:
C

array([[ 1, 99],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [68]:
print(B)

print("\n")

print(B[[1,3],[0,2]])

print("\n")

print(np.array([B[1,0] , B[3,2]]))

[[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[ 4 12]


[ 4 12]


In [70]:
print(B)

print("\n")

print(B[[1,1],[2,2]])

print("\n")

print(np.array([B[1,2] , B[1,2]]))


[[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[6 6]


[6 6]


In [73]:
# Logical Indexing / Boolean Indexing 

print(B)

print("\n")

Bool_Index = B > 9

print(Bool_Index)

[[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[False  True False]
 [False False False]
 [False False False]
 [ True  True  True]]


In [74]:
B[Bool_Index]

array([99, 10, 11, 12])

In [75]:
B[B>9]

array([99, 10, 11, 12])

In [81]:
B

array([[ 1, 99,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
B + np.array([1,1,1])

array([[  2, 100,   4],
       [  5,   6,   7],
       [  8,   9,  10],
       [ 11,  12,  13]])

### Transposing an Array ( Changing the rows into columns and vice versa )

In [42]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.transpose(B)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
B.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Change the dimension of an Array 

In [45]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
B.shape

(2, 3)

In [46]:
B.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

### Flatten an Array 

In [48]:
B.ravel()

array([1, 2, 3, 4, 5, 6])

In [49]:
B.ravel().shape

(6,)

### Appending rows/columns to an Array 

In [34]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
## Appending to end of Row 

np.append(B,[[7,8,9]] , axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
## Appending to end of column 

np.append(B,[[7],[8]] , axis=1)

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [36]:
# Arithmetic Operators 

B 

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
B + np.array([1,1,1])

array([[2, 3, 4],
       [5, 6, 7]])

In [39]:
Array_1 = np.array([[1,2,3] ,[4,5,6]])

Array_1

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
Array_2 = np.array([[7,8,9] ,[10,11,12]])

Array_2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [41]:
Array_1 + Array_2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [42]:
np.add(Array_1 , Array_2)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [43]:
Array_2 - Array_1

array([[6, 6, 6],
       [6, 6, 6]])